apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnist-training-logs
  namespace: kubeflow-user
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rok
  resources:
    requests:
      storage: 2Gi
---
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: mnist-dist
  namespace: kubeflow-user
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccount: default-editor
          containers:
            - name: pytorch
              image: dpoulopoulos/mnist-fsdp:v0.0.3
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /logs
                  name: training-logs
              command: ["python", "/opt/mnist.py"]
              args:
                - "--lr"
                - "0.0001"
                - "--epochs"
                - "4"
                - "--batch_size"
                - "128"
              resources:
                requests:
                  cpu: 4500m
                  memory: 16Gi
                limits:
                  cpu: 4500m
                  memory: 16Gi
                  nvidia.com/gpu: 1
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
            - name: training-logs
              persistentVolumeClaim:
                claimName: mnist-training-logs
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccount: default-editor
          containers:
            - name: pytorch
              image: dpoulopoulos/mnist-fsdp:v0.0.3
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /logs
                  name: training-logs
              command: ["python", "/opt/mnist.py"]
              args:
                - "--lr"
                - "0.0001"
                - "--epochs"
                - "4"
                - "--batch_size"
                - "128"
              resources:
                requests:
                  cpu: 4500m
                  memory: 16Gi
                limits:
                  cpu: 4500m
                  memory: 16Gi
                  nvidia.com/gpu: 1
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
            - name: training-logs
              persistentVolumeClaim:
                claimName: mnist-training-logs
